name: Dictionary CLI CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # 1. BUILD STEP
    - name: Build Step - Install and Compile
      run: |
        echo "=== Starting Build Phase ==="
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        python -m pip install -r requirements.txt
        python -m pip install -e .
        echo "=== Build Phase Complete ==="

    # 2. TEST SUITE
    - name: Test Step - Run Test Suite
      run: |
        echo "=== Starting Test Phase ==="
        python -m pytest tests/ -v --cov=src/dictionary_cli --cov-report=term-missing
        echo "=== Test Phase Complete ==="

    # 3. ARTIFACT PRODUCTION
    - name: Artifact Step - Create Distribution
      run: |
        echo "=== Starting Artifact Creation Phase ==="
        python setup.py sdist bdist_wheel
        echo "Created artifacts:"
        ls -l dist/
        echo "=== Artifact Creation Complete ==="

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dictionary-cli-package
        path: |
          dist/*.whl
          dist/*.tar.gz
        retention-days: 5

    - name: Build Summary
      run: |
        echo "=== Build Pipeline Summary ==="
        echo "1. Build: ✓ Completed"
        echo "2. Tests: ✓ Completed"
        echo "3. Artifacts: ✓ Generated"
        echo "Artifacts available in dist/:"
        ls -l dist/

